### ISSUE TITLE
undefined method `input' for #<ActionView::Helpers::FormBuilder:0x228427c8>

### ISSUE THREAD

**Issue by choward7** [zpaulovics/datetimepicker-rails#31]
I'm new to Rails. Where should the following code be placed?

<input class="datetimepicker" type="text" >

<script type="text/javascript">
    $('.datetimepicker').datetimepicker();
</script>

I believe this may be the issue but here's the erro that  I'm receiving. 

NoMethodError in Appts#new
Showing /vagrant/projects/PremierDerm/app/views/appts/_form.html.erb where line #26 raised:

undefined method `input' for #<ActionView::Helpers::FormBuilder:0x228427c8>
Extracted source (around line #26):

     </div>
   
       <div class="field">
         <%= f.input :start_date_time, :as => :datetime_picker %>
       </div>
     <div class="actions">
       <%= f.submit %>

Trace of template inclusion: app/views/appts/new.html.erb

**Comment by zpaulovics** [comment]
Hi,

Really "input" is your filed name?

Zoltan
