### ISSUE TITLE
How to close datetimepicker after selecting date?

### ISSUE THREAD

**Issue by pablosalgadom** [zpaulovics/datetimepicker-rails#35]
Hello, i'm using your gem but i can't find a way to close the date window after select a date, can you lead me how to do that?

Thank you in advance :D

**Comment by zpaulovics** [comment]
If it is working correctly you just should click outside the overlay form.


Üdv,

Zoli

**Comment by pablosalgadom** [comment]
Thank you for the response, but i'm looking for something more automatic, it's possible to do that?

**Comment by zpaulovics** [comment]
Yes, just call the hide function on the object.
