### ISSUE TITLE
onChange event not firing

### ISSUE THREAD

**Issue by panceri** [zpaulovics/datetimepicker-rails#39]
Hi, 
   how i can hook DateChange event?? I tried:
```javascript
  $('.date').datetimepicker({
      locale: 'pt-BR',
      format: 'DD/MM/YYYY HH:mm:ss A',
      onChange = function(e){
            console.log("Fire");
      }
    });

  $('.date').datetimepicker({
      locale: 'pt-BR',
      format: 'DD/MM/YYYY HH:mm:ss A',
    }).on("change", function(e){
         console.log("Fire again");
    });
```

  but not working...

**Comment by zpaulovics** [comment]
Try it again by using the current eonasdan branch. This branch is upgraded to version 4.0.0, but it is release candidate state at the moment.

**Comment by sonuoommen** [comment]
Hi,

I have this issue while using the gem where say one of the validation fails and the page is re rendered. Now the datetime value is messed up like => 12/02/2015 hh:mm A. Do you have any solution to this ?

**Comment by panceri** [comment]
Yeah, it works thanks!!
