### ISSUE TITLE
DateTime value getting messed up after rendering the page in case of an error

### ISSUE THREAD

**Issue by sonuoommen** [zpaulovics/datetimepicker-rails#42]
Hi,

I have this issue while using the gem where say one of the validation fails and the page is re rendered. Before the create actionit looked like 12/02/2015 04:13 PM, create action fails due to validation and now the DateTime field has value 12/02/2015 hh:mm

**Comment by zpaulovics** [comment]
Hi,

I cloud not reproduce the issue.

Using:
 - Rails 4.2
 - Simpleform 3.1
 - Momentjs-rails 2.9
 - datetimepicker-rails 4.0.0.RC2 (available in eonasdan branch)

Tested by using the demo application at: https://github.com/zpaulovics/dateTimeDemo

Zoltan

**Comment by sonuoommen** [comment]
Hi,

I fixed it a while ago, sorry couldn't reply immediately. It was due to
en.yml file, i changed the format and it was working. I mean i am getting
it right while re rendering it. I'll close the issue. Thanks for the reply.

Cheers,
Sonu

**Comment by sonuoommen** [comment]
If you want to reproduce it write the folllowing in en.yml

timepicker:
    dformat: "hh:mm A"
    pformat: "hh:mm A"
