### ISSUE TITLE
Simple_Form dependecy

### ISSUE THREAD

**Issue by panceri** [zpaulovics/datetimepicker-rails#44]
In development enviroment i dont need simple_form gem, but when i change to production mode i have unitializing constant SimpleFor (My app dont use this Gem).  For now, i include this dependency in my Gemfile and works, but i think its wrong...

**Comment by zpaulovics** [comment]
Hi,
I do not think so. 
But if you do not use SimpleForm, you should not use this gem. You should use this https://github.com/TrevorS/bootstrap3-datetimepicker-rails gem instead. It manages the asset pipeline that you need then.
Zoltan

**Comment by panceri** [comment]
Hahaha sorry, i think somebody changed this dependency on my project. Thanks
