### ISSUE TITLE
Git checkout doesn't work anymore

### ISSUE THREAD

**Issue by tangopium** [zpaulovics/datetimepicker-rails#52]
If I use the following entry in my gem file, the fetch doesn't work:

    gem 'datetimepicker-rails', github: 'zpaulovics/datetimepicker-rails', branch: 'master', submodules: true

The error is the following:

    Fetching git://github.com/zpaulovics/datetimepicker-rails.git
    fatal: Could not parse object 'e41ba7f805d1eca19153ff91b27423a4aff5e4b6'.

**Comment by wccinc** [comment]
Try running: `bundle update datetimepicker-rails` to update the revision info in your Gemfile.lock.  That fixed if for me.

**Comment by robguilfoyle** [comment]
^ worked for me as well.
