### ISSUE TITLE
Good working example for datepicker-rails and bootstrap 3 + simple_form?

### ISSUE THREAD

**Issue by rubytastic** [zpaulovics/datetimepicker-rails#54]
Is there, or can anyone provide a 
Good working example for datepicker-rails and bootstrap 3 + simple_form?
All the examples here and on stackoverflow + the example app all fail.

Followed all instructions, only moved the assets from vendor in my regular asset pipeline ( since i need some custom paths )

Using this:
```
  = f.input :expire_at, as: :date_picker,
            :label => false,
            input_html: {data: {date_options: { defaultDate: '12-01-2015', showClose: true }}}

```

There are 2 problems
* The fontawsome throws error and not showing up 404 ( where is the path set, in the gem?) 
* The default date is not showing up at all

Any thought on resolving above? lots of people have issue with getting this to work with rails perhasp a single writeup with the steps needed would help alot.

**Comment by zpaulovics** [comment]
Hi rubytastic,

1. You are right. I have fixed the bug of the option handling. 
2. Regarding the fontawsome icon library the Gem does not place the icon files to the asset pipeline. It is your responsibility. The GEM only use the alternative icon names for fontawsome.

Regards,
Zoltan
