### ISSUE TITLE
Sprockets::FileNotFound - couldn't find file 'moment' with type 'application/javascript':

### ISSUE THREAD

**Issue by kikocastro** [zpaulovics/datetimepicker-rails#56]
Hey there,

just ran the installer, but i'm getting this error

`Sprockets::FileNotFound - couldn't find file 'moment' with type 'application/javascript':`

When I save moment.js to the folder it runs normally

**Comment by robinbortlik** [comment]
I think you forgot to add 

```gem 'momentjs-rails', '~> 2.9',  :github => 'derekprior/momentjs-rails'``` 

to your gemfile. You can read about it in Readme in section Dependency.

**Comment by kikocastro** [comment]
Oh, I think I missunderstood it. Perhaps " Includes the dependency reference in its Gemfile:" could be changed to " You must include the dependency reference in your Gemfile:"? 
Thanks for the reply! It's a very handy gem.

**Comment by brntsllvn** [comment]
Agree with @kikocastro on the gem's handiness, but I ran into the same error and second his request for a revision to the language preceding the dependency per his suggestion: "You must include the dependency reference in your Gemfile." Thanks again for everything.
