### ISSUE TITLE
ReferenceError: Can't find variable: module

### ISSUE THREAD

**Issue by dongli** [zpaulovics/datetimepicker-rails#74]
I followed the instructions on the README, and encountered the error:

![screen shot 2016-01-19 at 2 50 23](https://cloud.githubusercontent.com/assets/367959/12411716/dd5b7c98-bebb-11e5-833b-05f34ca45729.png)

![wechat_1453188085](https://cloud.githubusercontent.com/assets/367959/12412282/6fafb9d4-bec0-11e5-9616-618c35ce8fc9.jpeg)

It comes from `momentjs`, but when I remove the `require` line for `bootstrap-datetimepicker`, the error is gone. Thanks in advance!

**Comment by redrick** [comment]
Hey I had exactly the same problem and as is written here https://github.com/derekprior/momentjs-rails/pull/43

that 2.11.1 momentjs solves it, well at least for me it did, I have it as runtime dependency inside gem, so I bulid gem here (`https://rubygems.org/gems/momentjs-rails-updated`)

they hopefully merge it or just refer to master of @egeek repo: `https://github.com/egeek/momentjs-rails`

hopefully helped a bit :)

**Comment by dongli** [comment]
Thanks for replying! I have used `bootstrap3-datetimepicker-rails` instead. Maybe I will give it a try.
